name: output 연습
on: push

jobs:
  create-output:
    runs-on: ubuntu-latest

    outputs:
      abc: ${{ steps.save-output.outputs.message }}

  use-output:
    runs-on: ubuntu-latest
    # 위의 job(create-output)에서 만든 outputs를 해당 job(use-output)에서 사용하기 위해선
    # 위 job(create-output)이 싪패하면 안되기 때문에 needs가 필요합니다.
    needs: create-output
    steps:
      - name: output 사용
        run: echo "이 job에서 사용할 output은 ${{ needs.create-output.outputs.abc }}입니다."
